### ISSUE TITLE
How to Run ?

### ISSUE THREAD

**Issue by JayRathod341997** [modelhub-ai/emotion-fer-plus#1]
How to run given a project in Anaconda Notebook?

**Comment by ahmedhosny** [comment]
Hello -
Please view the instructions to run models [here](http://app.modelhub.ai/), also copied below.

1. Install Docker. (CE is sufficient)
2. Install Python 2.7 or 3.6 or higher, if not already installed.
3. Download the [modelhub start script](https://raw.githubusercontent.com/modelhub-ai/modelhub/master/start.py) and place it into a new folder.
4. Open a terminal and run the following:

- to interact with the model using the modelhub REST API: ([docs](https://modelhub.readthedocs.io/en/latest/modelhubapi.html#rest-api))
python start.py squeezenet

- or to interact with the model using the modelhub python API in a jupyter notebook: ([docs](https://modelhub.readthedocs.io/en/latest/modelhubapi.html#python-api))
python start.py squeezenet -e
